# Tipos de variables
* Numericas
* Enteras
* Caracteres
* Logicos
* Complejos
Para declarar una variable basta con escribir el nombre que le queramos dar , después se escribe <- o = para decir que lo que coloquemos a la derecha de esta expresión será el valor 

In [4]:
#Numericos
altura <- 1.78
#Enteros
edad = 18
#Caracteres
nombre <- "Luis"
#Logicos
bandera = TRUE
#Complejos
b <- 1 + 2i

# Operaciones Matemáticas Básicas

In [5]:
a <- 10
b <- 3
suma <- a + b
print(suma)
resta <- a - b
print(resta)
multiplicacion <- a * b
print(multiplicacion)
division <- a / b
print(division)
potencia <- a^b
print(potencia)
modulo <- a %% b
print(modulo)
division_entera <- a %/% b
print(division_entera)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1000
[1] 1
[1] 3


# Operaciones con Vectores
Para crear un vector basta con colocar c() y dentro de los paréntesis los valores que le quieras asignar a cada campo

In [12]:
v1 <- c(1, 2, 3)
v1
v2 <- c(4, 5, 6)
v2
suma_vector <- v1 + v2
suma_vector
producto_vector <- v1 * v2
producto_vector
raiz_cuadrada <- sqrt(v1)
raiz_cuadrada

[1] 1 2 3

[1] 4 5 6

[1] 5 7 9

[1]  4 10 18

[1] 1.000000 1.414214 1.732051

# Operaciones con Matrices
Para crear una matriz basta con colocar matrix(n:n,nrow = 2) y dentro de los paréntesis se coloca la progresión de números que irán en cada campo y, después de la coma, se coloca la cantidad de filas que tendrá 

In [11]:
A <- matrix(1:4, nrow = 2)
print("Matriz A")
A
B <- matrix(5:8, nrow = 2)
print("Matriz B")
B
multiplicacion_matrices <- A %*% B
print("multiplicacion de matriz A y B")
multiplicacion_matrices
transpuesta <- t(A)
print("transpuesta de A")
transpuesta
inversa <- solve(A)
print("inversa de A")
inversa
determinante <- det(A)
print("determinante de A")
determinante

[1] "Matriz A"


[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] "Matriz B"


[,1] [,2]
[1,] 5    7   
[2,] 6    8

[1] "multiplicacion de matriz A y B"


[,1] [,2]
[1,] 23   31  
[2,] 34   46

[1] "transpuesta de A"


[,1] [,2]
[1,] 1    2   
[2,] 3    4

[1] "inversa de A"


[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

[1] "determinante de A"


[1] -2

# Operaciones con Listas
Para crear una lista basta con colocar list() y dentro de los paréntesis los valores que le quieras asignar a cada campo

In [22]:
mi_lista <- list(1, "Hola", TRUE)
mi_lista
elemento <- mi_lista[[3]]
elemento
mi_lista <- c(mi_lista, "Nuevo elemento")
mi_lista

[[1]]
[1] 1

[[2]]
[1] "Hola"

[[3]]
[1] TRUE

[1] TRUE

[[1]]
[1] 1

[[2]]
[1] "Hola"

[[3]]
[1] TRUE

[[4]]
[1] "Nuevo elemento"

# Bucle for
Primero se coloca la palabra reservada for después dentro de los paréntesis se colocará el nombre de la variable la cual se modificará cada iteración y después se usa la palabra in para decir en qué intervalo se ejecutara el bucle, y por último se abren unas llaves para decir que será lo que se ejecutará en cada iteración

In [24]:
for (i in 1:5) {
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


# Bucle while
Primero se coloca la palabra reservada while después dentro de los paréntesis se colocará la condición a cumplir para que se ejecute el ciclo y por último se abren unas llaves para decir que será lo que se ejecutará en cada iteración

In [25]:
i <- 1
while (i <= 5) {
  print(i)
  i <- i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


# Condiciones
Primero se coloca la palabra reservada if después dentro de los paréntesis se colocará la condición a cumplir para que se ejecute un bloque de código en específico y por último se abren unas llaves para decir que será lo que se ejecutará , después de un if se puede colocar un else ,que se ejecutará en el caso de que la condición del if no se cumpla

In [28]:
edad <- 18
if (edad >= 18) {
  print("es mayor de edad")
} else {
  print("es menor de edad")
}

[1] "es mayor de edad"


# Funciones
Para crear una función primero se escribe el nombre que le queremos dar , después se le da el valor la función que deseamos hacer ,se usa la palabra reservada function y se coloca un par de paréntesis , donde dentro de ellos se coloca los valores que entraran como parámetro y se abren llaves para definir que será lo que se ejecute cuando se llame la función, en el caso que deseen retornar un valor se usa la palabra reservada return y se le coloca al lado la variable o el valor que deseamos retornar 

In [13]:
mi_funcion <- function(a, b) {
  return(a + b)
}
resultado <- mi_funcion(5, 5)
print(resultado)  

[1] 10


# Ejercicio sencillo 
Calcular la media de un vector de números.

In [2]:
numeros <- c(10, 20, 30, 40, 50)

media <- mean(numeros)

print(media)

[1] 30
